CREATE  TABLE IF NOT EXISTS WEATHER_DETAILS3(timestamp timestamp,
        source_id int NOT NULL,
        precipitation varchar(255),
        pressure_msl float,
        sunshine  varchar(255),
        temperature float,
        wind_direction float,
        wind_speed float,
        cloud_cover float,
        dew_point float,
        relative_humidity float,
        visibility float,
        wind_gust_direction float,
        wind_gust_speed float,
        condition varchar(255));